### ISSUE TITLE
treeview selection can be changed by 'mouseup'

### ISSUE THREAD

**Issue by MM-RYO** [lidorsystems/integralui-web-angular#17]
Steps:

1. expand 'Item 1 > Item 2 > Item 3'
2. select 'Item 4'
3. mouse down on outside of treeview control and hold it.
4. drop it on item which does not have children items

actual: the selection has changed
expect: the selection shouldn't be changed. if it has changed the selection event should be fired.

Sample:
https://stackblitz.com/edit/integralui-treeview-fast-load-pkqegr

**Comment by Lidor-Systems** [comment]
Its a bug. The mouse up event updates the selection (mostly usable when multiple items are selected), but it shouldn't act when the mouse down is clicked outside of the TreeView.

The fix will be available in next update.

**Comment by Lidor-Systems** [comment]
The fix is now included in v20.2.
