### ISSUE TITLE
beforeExpand event is not triggered 

### ISSUE THREAD

**Issue by aandriichuk** [lidorsystems/integralui-web-angular#2]
Hello. For some reason beforeExpand event is not triggered but itemAddedEvent works fine. Do you have any ideas?

// treeview.component.html

<div #application>
    <iui-treeview [items]="items" [appRef]="applicationRef" (itemAdded)="itemAddedEvent($event)" (beforeExpand)="beforeExpandEvent($event)" #treeview>
            <template let-item>
                <div (mouseenter)="hoverItem=item" (mouseleave)="hoverItem=null">
                    <span [ngClass]="item.icon"></span>
                    <span *ngIf="item!=editItem">{{item.text}}</span>
                    <input *ngIf="item==editItem" type="text" [(ngModel)]="item.text" (keydown)="editorKeyDown($event)" (blur)="editorLostFocus()" [iuiFocus]="editorFocused" onFocus="this.setSelectionRange(0, this.value.length)" />
                    <div class="toolbar" *ngIf="item==hoverItem" #treeitem>
                        <span class="item-button item-button-edit" (click)="showEditor(item)"></span>
                    </div>
                </div>
            </template>
    </iui-treeview>
</div>

// treeview.component.html

import { Component, ViewEncapsulation, ViewChild, ViewChildren, ViewContainerRef, OnInit } from '@angular/core';
import { IntegralUITreeView } from 'integralui-web/components/integralui.treeview';
import { FileExplorerService } from '../file-explorer.service';

@Component({
    selector: 'treeview',
    template: require('./treeview.component.html'),
    styles: [require('./treeview.component.css')],
    encapsulation: ViewEncapsulation.None
})
export class TreeViewComponent implements OnInit {

    // An Array object that holds all item objects shown in TreeView
    // It is set as a list of any custom objects, you can use any custom fields and data bind them with TreeView using its properties
    private items: any[];

    // Get a reference of application view
    @ViewChild('application', { read: ViewContainerRef }) applicationRef: ViewContainerRef;
    @ViewChild('treeview') treeview: IntegralUITreeView;

    // Editor settings
    private isEditActive: boolean = false;
    private editItem = null;
    private originalText: string = '';
    private editorFocused: boolean = false;
    private hoverItem = null;

    // Initialize items in component constructor
    constructor(private fileExplorerService: FileExplorerService) {
        this.items = []; 
    }

    ngOnInit(): void {
        this.fileExplorerService.getTreeNodes().then(nodes => this.showItems(nodes));
    }

    showItems(nodes) {
        for (let entry of nodes) {
            this.treeview.addItem(entry);
        }
    }

    showEditor(item) {
        this.originalText = item.text;
        this.isEditActive = true;
        this.editItem = item;
        this.editorFocused = true;
    }

    closeEditor() {
        this.editItem = null;
        this.originalText = '';
        this.editorFocused = false;
    }

    editorKeyDown(e) {
        if (this.editItem) {
            switch (e.keyCode) {
            case 13: // ENTER
                this.closeEditor();
                break;

            case 27: // ESCAPE
                this.editItem.text = this.originalText;
                this.closeEditor();
                break;
            }
        }
    }

    editorLostFocus() {
        if (this.editItem)
            this.editItem.text = this.originalText;

        this.closeEditor();
    }

    itemAddedEvent(e) {
        console.log("itemAddedEvent: " + e.item.text);
    }

    beforeExpandEvent(e) {
        console.log("beforeExpandEvent: " + e.item.text);
    }
}

**Comment by Lidor-Systems** [comment]
Upon checking the code, we notice that code that fires expand/collapse events was disabled in current version, during internal testing. Unfortunately, this remained when current beta version was released.

The fix will be included as part of new update coming next week. This update will also include the Grid and TreeGrid components.

**Comment by Lidor-Systems** [comment]
We have just released v0.9.0, now the expand/collapse events are fired whenever item is expanded or collapsed.

**Comment by aandriichuk** [comment]
Thank you. I'll try

**Comment by aandriichuk** [comment]
I also want ask you do you have examples how to use following methods 
collapse 
expand 
findItemById
findItemByText
insertItemAfter
insertItemBefore
insertItemAt
removeItem
scrollPos
toggle

It seems they were not available in previous version but described in documentation here http://www.lidorsystems.com/support/articles/angular/treeview/treeview-component.aspx.

**Comment by Lidor-Systems** [comment]
As it is explained in the article:
- At first Import the IntegralUI TreeView component at heading of your application component

`import { IntegralUITreeView } from 'integralui-web/components/integralui.treeview';`

- Add a variable in HTML specification of the TreeView component
```
  <iui-treeview [items]="data" #treeVariable>
      <template let-item>
           {{item.text}}
      </template>
</iui-treeview>
```
- Use this variable to get a reference to the TreeView

`@ViewChild('treeVariable') treeview: IntegralUITreeView;`

- Use the reference to access public methods
```
        let item = {
            text: "New Item"
        }

        this.treeview.insertItemAt(item, 0);
```
Here are method signatures:
```
   insertItemAt(item, index, parent?)
   insertItemBefore(item, refItem)
   insertItemAfter(item, refItem)
   removeItem(item)
   removeItemAt(index, parent?)
```

Methods mentioned:
```
collapse(item?)
expand(item?)
toggle(item?)
scrollPos(pos?)
```

are not yet available. We will update the beta version later today, and you can use it.

Documentation is still in works. Soon we will publish a complete API for each component and a User Guide.

**Comment by Lidor-Systems** [comment]
We have released v0.9.012. Whenever a version is released, check out the Change_Log for more information.

The expand/collapse methods are now available, along with scrollPos method. Their use is simple, for example:

```
// To expand all items
this.treeview.expand();

// To expand specific item
this.treeview.expand(item);

// To change scroll position from code
// this will move horizontal scroll to 100px and vertical scroll to 500px
this.treeview.scrollPos({ x: 100, y: 500 });

// To get current scroll positon
this.treeview.scrollPos();

```

**Comment by Lidor-Systems** [comment]
To use findItemById or findItemByText, at first item objects must have its id or text field set. For example:

```
this.items.length = 0;
for (let i = 1; i <= 100; i++)
      this.items.push({ id: i, text: "Item" + i });

let item = this.treeview.findItemById(5);
console.log(item);
```

**Comment by aandriichuk** [comment]
Thank you!
