### ISSUE TITLE
TreeGrid & TreeView Mobile

### ISSUE THREAD

**Issue by NexPlex** [lidorsystems/integralui-web-angular#5]
Hi
After looking into it more I think I should be using TreeGrid. I really like your TreeGrid and TreeView. I have them working good on the PC.

1. I’m not able to get them working on mobile phone or tablet very well. Some features work. Expand and collapse not working on TreeGrid and difficult on TreeView. Is it possible to support Expand and collapse easily on mobile phone to tablet?

 2. will you please provide some examples of using these parameters and what spacing referring to?

this.treegrid.exportToJSON(columnFields?: any, rowFields?: any, spacing?: any, flat?: boolean): string;

3., the code "treegrid-events.ts" works correctly on my system. The code I really want to use,  "treegrid-add-row-dynamically" gives me the error below. Any suggestion on what is causing the error and how to correct it?

![image](https://user-images.githubusercontent.com/34607168/36626556-bbdb76c4-18e9-11e8-9f4a-1605dcd3ee60.png)

And this code treeview-filter.ts give me the error below. Any suggestion on what is causing the error and how to correct it?

![image](https://user-images.githubusercontent.com/34607168/36626455-d17d5350-18e7-11e8-9f7e-cb25c5cba862.png)

Thank you

Chris

**Comment by Lidor-Systems** [comment]
1. Probably some features don't work as expected because we don't have event handlers for touch events. This will be implemented soon and will be part of IntegralUI Web 18.1 coming in March 2018. 

2. Here is an example:

```
        let colFields: Array<string> = ['id', 'headerText'];
        let rowFields: Array<string> = ['id', 'pid', 'text'];
        let spacing: string = '  ';

        let data = this.treegrid.exportToJSON(colFields, rowFields, spacing, true);
```

The fields acts like a filter, the result will show only the specified field names. The spacing is used to make the resulting string more readable. The flat parameter determines whether the result is a tree hierarchy or a flat list.

3. We suspect that you don't have **IntegralUICommonService** set in your sample constructor:

```
import { IntegralUICommonService } from '../../integralui/services/integralui.common.service';

constructor(private commonService?: IntegralUICommonService){
  . . .
}
```

We are using this service in treegrid-add-row-dynamically sample to call a function that creates a unique id for the new row.

As for the filter sample, check out whether you have a reference to the **IntegralUIFilterService**:

```
import { IntegralUIFilterService } from '../../integralui/services/integralui.filter.service';

    constructor(protected filterService: IntegralUIFilterService){
  . . .
}
```

We are using this service to call advanced filtering functions that are already built-in (part of the filter service) to create custom filter operations.

**Comment by NexPlex** [comment]
For issue 3 I am using the code exactly as found in "integralui-web-trial\IntegralUI Web 17.4 - TRIAL\Angular\quickstart\src\app\samples\treegrid" directory. I verified the import and constructor look correct. 

Any other suggestions? 

I'm using angular-webpack-starter and angular 4.4.6. 

Simular configuration can be found here: https://github.com/ansrivas/angular2-flask.

Thank you

**Comment by Lidor-Systems** [comment]
We couldn't run angular2-flask project, it states that 'sudo' is not recognized, even after installing it. Probably the reason is because we are using Windows machine. Unfortunately we don't have a Linux machine available to test it.

Try to add/remove parts of that sample one by one, to see what part of the code may cause this error.

**Comment by NexPlex** [comment]
To use angular2-flask project for testing of intergralui, you don't need the Python API backend. Just the npm front end with Angular and Webpack. 

if you want to setup the Python backend API server on windows (i use windows) you need to install python and pip first. then run  "pip install -r requirements.txt" (leave off the sudo) from the backend directory. 

I will do so additional testing and let you know what I find out.

**Comment by NexPlex** [comment]
I am able to get "treegrid-add-row-dynamically" to work by adding **providers: [IntegralUICommonService]**

I'm not very strong in Angular. does this make sense to you? You see any issues or concerns with this providers property?

code snipit:
        </div>
    `,
    **providers: [IntegralUICommonService],**
    encapsulation: ViewEncapsulation.None
})

**Comment by Lidor-Systems** [comment]
It is OK. 

This service is set within providers section of InteralUICore module. In this way any component can use it, which is done when you import the IntegralUI module in your app.

It doesn't matter if you add it in your component inside providers section, based on Angular specifications, it just creates another instance of the service. This service contains methods for general use, and doesn't impact the overall functionality. 

If this solves the problem, continue with it. It doesn't create any issues regarding component functionalities.

**Comment by NexPlex** [comment]
I cannot loadData from data created with exportToJSON

Test code:
       this.treegrid.loadData(this.flatData);
        this.mystring = this.treegrid.exportToJSON('','','',true);
// different tries on load
        this.treegrid.loadData(this.mystring);
        this.treegrid.loadData(JSON.parse(this.mystring));
        this.treegrid.loadData(JSON.parse(this.mystring)[1]);
        this.treegrid.loadData(JSON.parse(this.mystring)[1].rows);

or false
       this.treegrid.loadData(this.flatData);
        this.mystring = this.treegrid.exportToJSON('','','',false);
// different tries on load
        this.treegrid.loadData(this.mystring);
        this.treegrid.loadData(JSON.parse(this.mystring));
        this.treegrid.loadData(JSON.parse(this.mystring)[1]);
        this.treegrid.loadData(JSON.parse(this.mystring)[1].rows);

   this.mystring=  '[ { "columns": [{"headerAlignment":"center","headerText":"Option","id":1,"width":180},{"contentAlignment":"center","headerAlignment":"center","headerText":"Action","id":2,"width":90},{"contentAlignment":"center","headerAlignment":"center","headerText":"Value","id":3,"width":90}] },{ "rows": [{"cells":[{"text":"Press 1a","cid":1},{"text":"Say","cid":2},{"text":"Script 1","cid":3}],"icon":"icons-medium people","id":1,"text":"Press 1a"},{"cells":[{"text":"Press 11","cid":1},{"text":"Say","cid":2},{"text":"Script 11","cid":3}],"id":11,"pid":1,"text":"Press 11"},{"cells":[{"text":"Press 12","cid":1},{"text":"Say","cid":2},{"text":"Script 12","cid":3}],"id":12,"pid":1,"text":"Press 12"},{"cells":[{"text":"Press 2","cid":1},{"text":"Say","cid":2},{"text":"Script 2","cid":3}],"icon":"icons-medium people","id":2},{"cells":[{"text":"Press 21","cid":1},{"text":"Say","cid":2},{"text":"Script 21","cid":3}],"id":21,"pid":2},{"cells":[{"text":"Press 22","cid":1},{"text":"Say","cid":2},{"text":"Script 22","cid":3}],"id":22,"pid":2},{"cells":[{"text":"Press 3","cid":1},{"text":"Say","cid":2},{"text":"Script 3","cid":3}],"icon":"icons-medium people","id":3},{"cells":[{"text":"Press 31","cid":1},{"text":"Say","cid":2},{"text":"Script 31","cid":3}],"id":31,"pid":3}] } ]';

 this.flatData = [
            {
                id: 1,
                icon: "icons-medium people",
                text: "Press 1",
                cells: [{ cid: 1, text: "Press 1" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 1" }]
            },
            {
                id: 11,
                pid: 1,
                text: "Press 11",
                cells: [{ cid: 1, text: "Press 11" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 11" }]
            },
            {
                id: 12,
                pid: 1,
                text: "Press 12",
                cells: [{ cid: 1, text: "Press 12" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 12" }]
            },
            {
                id: 2,
                icon: "icons-medium people",
                cells: [{ cid: 1, text: "Press 2" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 2" }]
            },
            {
                id: 21,
                pid: 2,
                cells: [{ cid: 1, text: "Press 21" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 21" }]
            },
            {
                id: 22,
                pid: 2,
                cells: [{ cid: 1, text: "Press 22" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 22" }]
            },
            {
                id: 3,
                icon: "icons-medium people",
                cells: [{ cid: 1, text: "Press 3" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 3" }]
            },
            {
                id: 31,
                pid: 3,
                cells: [{ cid: 1, text: "Press 31" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 31" }]
            }
        ];

**Comment by NexPlex** [comment]
How do i loadData from data created with exportToJSON().Tried all these combinations none seem to work.

        this.treegrid.loadData(this.flatData); //works
        this.mystring = this.treegrid.exportToJSON();

// tried all these none worked.
        this.treegrid.loadData(JSON.parse(this.mystring));
        this.treegrid.loadData(JSON.parse(this.mystring)[1]);
        this.treegrid.loadData(JSON.parse(this.mystring)[1].rows);

// also tried
        this.treegrid.exportToJSON('','','',true)

        this.treegrid.loadData(JSON.parse(this.mystring));
        this.treegrid.loadData(JSON.parse(this.mystring)[1]);
        this.treegrid.loadData(JSON.parse(this.mystring)[1].rows);

       this.columns = [
            { id: 1, headerText: "Option", headerAlignment: "center", width: 180 },
            { id: 2, headerText: "Action", headerAlignment: "center", contentAlignment: "center", width: 90 },
            { id: 3, headerText: "Value", headerAlignment: "center", contentAlignment: "center", width: 90 },


        ];

this.mystring= 
 '[ 
{ "columns": [{"headerAlignment":"center","headerText":"Option","id":1,"width":180},{"contentAlignment":"center","headerAlignment":"center","headerText":"Action","id":2,"width":90},{"contentAlignment":"center","headerAlignment":"center","headerText":"Value","id":3,"width":90}] },{ "rows": [{"cells":[{"text":"Press 1a","cid":1},{"text":"Say","cid":2},{"text":"Script 1","cid":3}],"icon":"icons-medium people","id":1,"text":"Press 1a"},{"cells":[{"text":"Press 11","cid":1},{"text":"Say","cid":2},{"text":"Script 11","cid":3}],"id":11,"pid":1,"text":"Press 11"},{"cells":[{"text":"Press 12","cid":1},{"text":"Say","cid":2},{"text":"Script 12","cid":3}],"id":12,"pid":1,"text":"Press 12"},{"cells":[{"text":"Press 2","cid":1},{"text":"Say","cid":2},{"text":"Script 2","cid":3}],"icon":"icons-medium people","id":2},{"cells":[{"text":"Press 21","cid":1},{"text":"Say","cid":2},{"text":"Script 21","cid":3}],"id":21,"pid":2},{"cells":[{"text":"Press 22","cid":1},{"text":"Say","cid":2},{"text":"Script 22","cid":3}],"id":22,"pid":2},{"cells":[{"text":"Press 3","cid":1},{"text":"Say","cid":2},{"text":"Script 3","cid":3}],"icon":"icons-medium people","id":3},{"cells":[{"text":"Press 31","cid":1},{"text":"Say","cid":2},{"text":"Script 31","cid":3}],"id":31,"pid":3}] }
 ]';

        this.rows = [];

        this.flatData = [
            {
                id: 1,
                icon: "icons-medium people",
                text: "Press 1",
                cells: [{ cid: 1, text: "Press 1" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 1" }]
            },
            {
                id: 11,
                pid: 1,
                text: "Press 11",
                cells: [{ cid: 1, text: "Press 11" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 11" }]
            },
            {
                id: 12,
                pid: 1,
                text: "Press 12",
                cells: [{ cid: 1, text: "Press 12" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 12" }]
            },
            {
                id: 2,
                icon: "icons-medium people",
                cells: [{ cid: 1, text: "Press 2" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 2" }]
            },
            {
                id: 21,
                pid: 2,
                cells: [{ cid: 1, text: "Press 21" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 21" }]
            },
            {
                id: 22,
                pid: 2,
                cells: [{ cid: 1, text: "Press 22" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 22" }]
            },
            {
                id: 3,
                icon: "icons-medium people",
                cells: [{ cid: 1, text: "Press 3" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 3" }]
            },
            {
                id: 31,
                pid: 3,
                cells: [{ cid: 1, text: "Press 31" }, { cid: 2, text: "Say" }, { cid: 3, text: "Script 31" }]
            }
        ];

**Comment by Lidor-Systems** [comment]
The loadData method works only with rows. The data that is exported contains columns and rows. So you need to extract them first and then use the loadData method. For example:

```
        // data is a string returned from exportToJSON method
        this.dataJSON = JSON.parse(data);

    load(){
        // Suspend the grid layout to increase performance
        this.treegrid.suspendLayout();

        // At first clear the current data from the grid
        this.treegrid.clearColumns();
        this.treegrid.clearRows();

        // Add columns based on the data
        for (let j = 0; j < this.dataJSON[0].columns.length; j++)
            this.treegrid.addColumn(this.dataJSON[0].columns[j]);

        // Add rows based on the data
        this.treegrid.loadData(this.dataJSON[1].rows, null, null, true);

        // Resume and update the grid layout with new data
        this.treegrid.resumeLayout();
    }
```

**Comment by Lidor-Systems** [comment]
loadData is designed in this way to accept only rows, because in most cases grid is updated with new rows in whole or for specific parent row, while the columns remain the same.

**Comment by NexPlex** [comment]
ok thank you, how can I add a hyperlink to a cell or trigger an event when a cell is clicked?

**Comment by Lidor-Systems** [comment]
Check out the treegrid-cell-templates.ts sample. There you can see different cells display different content, based on template settings. 

In case of a hyperlink, just add <a> tag inside the cell template. As for events, just add (mousedown) or (click) event inside elements in cell template:

```
                    <ng-template let-cell [iuiTemplate]="{ type: 'cell' }">
                            <div (mousedown)="cellClicked($event, cell)">
                                <a href="http://hyperlink-address.com">Hyperlink</a>
                            </div>
                    </ng-template>
```

Then add cellClicked function in your code.

**Comment by NexPlex** [comment]
OK that makes sense thank you. Is there an easy way to have the first row of an expanded row be a new header with header formatting?

For example you have 10 rows, click and expand the fifth row and then you see a new header in row 6 for the expanded rows.

**Comment by Lidor-Systems** [comment]
We presume you are referring to Master-Detail view, meaning where rows can have a different grid with its own header and data in different columns? 

This feature is not yet available, but it is planned for future releases.

**Comment by NexPlex** [comment]
OK thank you, is there a way to change the color of a row based on a row value?

**Comment by Lidor-Systems** [comment]
No, at this moment.

You can change the appearance of column or row cells, from the template, but not for entire row.

**Comment by NexPlex** [comment]
I'm hoping you can help me make this look better. The cells with blue backgrounds are header rows.
I'd like all cells in these header rows to have the same color background. how can I do that? Any other suggestion to make it look better?

![image](https://user-images.githubusercontent.com/34607168/37251177-9159ebd8-24bf-11e8-920b-efca46a96bec.png)

html
```
 <iui-treegrid [columns]="columnsCamp" [rows]="rows" [controlStyle]="treegridStyle" [showFooter]="false" [rowHeight]="26"
                              [allowDrag]="true" [allowDrop]="true" #treegrid>
                    <ng-template let-column [iuiTemplate]="{ type: 'header' }">
                        <span>{{column.headerText}}</span>
                    </ng-template>
                    <ng-template let-cell [iuiTemplate]="{ type: 'cell' }" >

                        <div [ngSwitch]="cell.cid" [ngStyle]="getStyleHeader(cell.header)" >
                            <div *ngSwitchCase="14" (dblclick)="onButtonsDblClick($event)" (mousedown)="onButtonsMouseDown($event)" >
                                <div *ngIf="cell.rid==currentEditRowID" >
                                    <button (mousedown)="saveRow(cell.rid)">Save</button>
                                    <button (mousedown)="cancelEdit(cell.rid)">Cancel</button>
                                </div>
                                <div *ngIf="cell.rid!=currentEditRowID">
                                    <div class="treegrid-ardyn-button-block" (mousedown)="editRow(cell.rid)">
                                        <span class="treegrid-ardyn-icons treegrid-ardyn-button-edit"></span>
                                    </div>
                                    <div class="treegrid-ardyn-button-block" (mousedown)="removeRow(cell.rid)">
                                        <span class="treegrid-ardyn-icons treegrid-ardyn-button-remove"></span>
                                    </div>
                                </div>
                            </div>
                            <div *ngSwitchDefault style="display:inline-block;">

                                <input *ngIf="cell.saved==false" class="treegrid-ardyn-cell-input" [(ngModel)]="cell.editText"
                                       [iuiFocus]="currentEditCell==cell" (focus)="selectContent($event)" (keydown)="editorKeyDown($event)"
                                       [ngStyle]="{ width: getCellWidth(cell) + 'px' }" />
                                <span *ngIf="cell.saved!=false" class="treegrid-ardyn-cell-text">{{cell.text}}</span>

                            </div>
                        </div>
                    </ng-template>
                </iui-treegrid>
```

.ts

```
  getStyleHeader(val: false) {
        let styles = {
            // CSS property names
            'background':  val ? '#2455b0' : '',     // italic
           // 'font-weight': val ? 'bold'   : 'normal',  // normal
            'color': val ? 'white' : 'black',
            'padding': val ? '-5,-5,-5,-5' : '',
            'text-align': val ? 'center' : ''
        };
        return styles;
    }
```

Data

```
        this.columnsCamp = [
            { id: 1, headerText: "", headerAlignment: "center", width: 200 },
            { id: 2, headerText: "Start", headerAlignment: "center", contentAlignment: "right", width: 100 },
            { id: 3, headerText: "End", headerAlignment: "center", contentAlignment: "right", width: 100 },
            { id: 4, headerText: "Script", headerAlignment: "center", contentAlignment: "center", width: 100 },
            { id: 5, headerText: "Retry", headerAlignment: "center", contentAlignment: "center", width: 100 },
            { id: 6, headerText: "No Answr", headerAlignment: "center", contentAlignment: "center", width: 100 },
            { id: 7, headerText: "Mach Retry", headerAlignment: "center", contentAlignment: "center", width: 50 },
            { id: 8, headerText: "All Retry", headerAlignment: "center", contentAlignment: "center", width: 50 },
            { id: 9, headerText: "Run Concurrent", headerAlignment: "center", contentAlignment: "center", width: 50 },
            { id: 10, headerText: "Fail Retry", headerAlignment: "center", contentAlignment: "center", width: 50 },
            { id: 11, headerText: "Mach Resp", headerAlignment: "center", contentAlignment: "center", width: 50 },
            { id: 12, headerText: "Messages", headerAlignment: "center", contentAlignment: "center", width: 50 },
            { id: 13, headerText: "Mach Succ", headerAlignment: "center", contentAlignment: "center", width: 50 },
            { id: 14, contentAlignment: "center", width: 100, fixedWidth: true }

        ];

                this.flatDataCamp = [
            {
                id: 1,
                icon: "icons-medium people",
                rowtype: 'camp',
                cells: [{ cid: 1, text: "NexPlex Clinic Appointment Reminder" }, { cid: 2, text: "09:00" }, { cid: 3, text: "21:00" }, { cid: 4, text: "Script 1" }, { cid: 14 }]
            },

            {
                id: 11,
                pid: 1,
                header: true,
                rowtype: 'InteractiveScript',
                cells: [{ cid: 1, text: "Show Interactive Script", header: false },
                  { cid: 2, text: "Description", header: true },
                  { cid: 3, text: "User Response\"", header: true },
                  { cid: 4, text: "Action", header: true },
                  { cid: 5, text: "Action Value", header: true },
                  { cid: 14 }]
            },


            {
                id: 111,
                pid: 11,
                rowtype: "InteractiveScript",
                cells: [{ cid: 1, text: "Outboud" },
                  { cid: 2, text: "Hello" },
                  { cid: 3, text: "Say" },
                  { cid: 4, text: "16" },
                  { cid: 5, text: "" },
                  { cid: 6, text: "" },
                  { cid: 7},
                  { cid: 8, text: "" },
                  { cid: 9, text: "" },
                  { cid: 10, text: "" },
                  { cid: 11, text: "" },
                  { cid: 12, text: "" },
                  { cid: 13, text: "" },
                  { cid: 14 }]
            },
            {
                id: 1111,
                pid: 111,
                rowtype: "InteractiveScript",
                cells: [{ cid: 1, text: "Ask for 3 or 4" },
                  { cid: 2, text: "1" },
                  { cid: 3, text: "Say" },
                  { cid: 4, text: "17" },
                  { cid: 14 }]
            },

            {
                id: 11111,
                pid: 1111,
                rowtype: "InteractiveScript",
                cells: [{ cid: 1, text: "Run Script 20" },
                  { cid: 2, text: "3" },
                  { cid: 3, text: "Say" },
                  { cid: 4, text: "20" },
                  { cid: 14 }]
            },
            {
                id: 11112,
                pid: 1111,
                rowtype: "InteractiveScript",
                cells: [{ cid: 1, text: "Thank you Script 21" },
                  { cid: 2, text: "4" },
                  { cid: 3, text: "Say" },
                  { cid: 4, text: "21" },
                  { cid: 14 }]
            },
                              {
                id: 1112,
                pid: 111,
                rowtype: "InteractiveScript",
                cells: [{ cid: 1, text: "Ask for 5 or 6" },
                  { cid: 2, text: "2" },
                  { cid: 3, text: "Say" },
                  { cid: 4, text: "18" },
                  { cid: 14 }]
            },
            {
                id: 11121,
                pid: 1112,
                rowtype: "InteractiveScript",
                cells: [{ cid: 1, text: "Thank you Script 22" },
                  { cid: 2, text: "5" },
                  { cid: 3, text: "Say" },
                  { cid: 4, text: "22" },
                  { cid: 14 }]
            },
            {
                id: 11122,
                pid: 1112,
                rowtype: "InteractiveScript",
                cells: [{ cid: 1, text: "Thank you Script 23" },
                  { cid: 2, text: "6" },
                  { cid: 3, text: "Say" },
                  { cid: 4, text: "23" },
                  { cid: 14 }]
            },
            {
                id: 12,
                pid: 1,
                header: true,
                rowtype: 'run',
                cells: [{ cid: 1, text: "Show Runs", header: false },
                  { cid: 2, text: "Created", header: true },
                  { cid: 3, text: "Modified", header: true },
                  { cid: 4, text: "Camp", header: true },
                  { cid: 14 }]
            },
            {
                id: 111,
                pid: 12,
                rowtype: 'run',
                cells: [{ cid: 1, text: "NexPlex Clinic Daily Call List - Monday" },
                  { cid: 2, text: "2018-01-27 21:51:42" },
                  { cid: 3, text: " 2018-01-27 21:51:42" },
                  { cid: 4, text: " 1" },
                  { cid: 14 }]
            },

            {
                id: 1112,
                pid: 111,
                header: true,
                rowtype: 'contact',
                cells: [{ cid: 1, text: "Contacts", header: false },
                  { cid: 2, text: "Name", header: true },
                  { cid: 3, text: "Contact Id", header: true },
                  { cid: 4, text: "Voice Phone", header: true },
                  { cid: 5, text: "Location", header: true },
                  { cid: 6, text: "Lang", header: true },
                  { cid: 7, text: "Date", header: true },
                  { cid: 8, text: "Time", header: true },
                  { cid: 9, text: "Provider", header: true },
                  { cid: 10, text: "Lead", header: true },
                  { cid: 14 }]
            },
                  {
                    id: 11121,
                    pid: 1112,
                    rowtype: 'contact',
                    cells: [{ cid: 1, text: "", header: false },
                    {cid: 2, text: "Won Kee Munger"},
                      {cid: 3, text: "895458974"},
                      {cid: 4, text: " 6199199036"},
                      {cid: 5, text: "3"},
                      {cid: 6, text: "EN-US"},
                      {cid: 7, text: "2017-08-16"},
                      {cid: 8, text: "13:30:00"},
                      {cid: 9, text: "650218"},
                      {cid: 10, text: "15"},
                      {cid: 14}]
                  }

       ];
```

**Comment by Lidor-Systems** [comment]
The best way to change the appearance of specific row is to have an option to change its style on individual level. As we mentioned before, this feature is not yet available.

We are working on a solution so that you can add a style object to each row, in this way you can update the row appearance on demand. It will work like this:

`	row.style = {
		background: '#000080',
		color: 'white',
		'font-weight': 'bold'
	}
`

internally this will be applied to [ngStyle] of the row element.

At the moment we cannot tell you for sure whether this feature wil be available in coming release of IntegralUI Web 18.1 on 20 March 2018, but if not, we will make sure it is ready right after, for which we will send you an update via e-mail.

Please send your request for this feature to **support@lidorsystems.com**, so we can notify you when it is ready.

**Comment by NexPlex** [comment]
okay, what is the easiest way to change the color of the header? should I override .iui-treegrid-column-header or is there a property I should use?

**Comment by Lidor-Systems** [comment]
The best way is using controlStyle property. You can add your own CSS class names and override the default appearance of each grid part: column header and footer, row, cells etc. 

For more information check out the [Styling ](http://www.lidorsystems.com/support/help/web/angular/guide/styling.aspx) article in online help.

Here is a priority list of style check (low-high):
1. Built-in CSS styles, each component has its own set of CSS classes that you can modify it in your code
2. controlStyle property, create your own CSS classes that will override the default ones
3. (not ready yet) style field for each column, row or cell object, which allows you to add inline styling to specific object during run-time based on your condition set.

**Comment by NexPlex** [comment]
is it possible to enable drag and drop by row
http://www.lidorsystems.com/support/help/web/angular/api/components/treegrid/properties/data-fields.aspx

**Comment by Lidor-Systems** [comment]
Yes, use the following:

```
// Disable specific row to drag
row.allowDrag = false;

// Prevent other rows to drop over specific row
row.allowDrop = false;
```

By default, both fields are set to true.

**Comment by NexPlex** [comment]
Will you please give some direction on controlling the height of the treegrid? 
I want it to be full page length until some max length is reached.  

Instead of scrolling is it possible to use pagination once the maximum length is reached?

**Comment by Lidor-Systems** [comment]
You can include the TreeGrid component inside a container (some &lt;div&gt; element) and set its width and height to 100%. Then control its height from the container via ngStyle directive, dynamically from code. So when for example window size changes, you can update the container height and this will also update the TreeGrid height.

As for Pagination, this feature is included in version release tomorrow, that is **IntegralUI Web 18.1**. When height changes, you can also set the number of rows per page via **pageSize** property. The QuickStart app will be updated tomorrow, so you can test it yourself.

**Comment by Lidor-Systems** [comment]
Just to let you know, the IntegralUI Web 18.1 is now released. 

The feature that allows changes to the grid row separately from other rows is now available. The column, row and cell objects now have a style field, which accepts an object for inline styling. This allows you to change the appearance of individual column, row or cell on demand. For example:

`
row.style = { background: '#000080', 'font-weight': 'bold' };
`

Internally it applies the object to ngStyle directive for the row element. 

You can use this feature to create sub-headings, like you mention in your previous post.

**Comment by NexPlex** [comment]
Okay, thank you. I'll check it out. any ideas on date drop-down and time drop-down for row edit?

**Comment by Lidor-Systems** [comment]
You can add any custom Angular component in grid cell. Here is a [date time component](https://dalelotts.github.io/angular-bootstrap-datetimepicker/) that you can use.

We will add our own DateTimePicker component scheduled for release in June 2018.

**Comment by NexPlex** [comment]
Hi, sorry I can't get this to work. Can you offer an example?

"You can include the TreeGrid component inside a container (some <div> element) and set its width and height to 100%. Then control its height from the container via ngStyle directive, dynamically from code. So when for example window size changes, you can update the container height and this will also update the TreeGrid height."

**Comment by Lidor-Systems** [comment]
Yes, here is how to include the TreeGrid in a container:

HTML

    <div #application [ngStyle]="{ width: '100%', height: containerSize.height + 'px' }">
        <iui-treegrid [appRef]="applicationRef" [controlStyle]="gridStyle" [columns]="columns" [rows]="rows" [rowHeight]="avgRowHeight" [paging]="paginationSettings" (pageChanged)="gridPageChanged($event)" #treegrid>
            <ng-template let-column [iuiTemplate]="{ type: 'header' }">
                {{column.title}}
            </ng-template>
            <ng-template let-cell [iuiTemplate]="{ type: 'cell' }">
                {{cell.text}}
            </ng-template>
            <ng-template let-column [iuiTemplate]="{ type: 'footer' }">
                {{column.footerText}}
            </ng-template>
        </iui-treegrid>
    </div>

The gridStyle determines the width and height of the TreeGrid. In this case they are both set to 100%, so that container size determines the grid size.

Angular

    public gridStyle: any = {
        general: {
            normal: 'treegrid-pgnt-normal'
        }
    }

CSS
```
 .treegrid-pgnt-normal
{
       width: 100%;
       height: 100%;
}
```

And then update the container size via code based on row count. If the count exceed max length, enable pagination:

Angular

    private updateContainerSize(){
        let list: Array<any> = this.treegrid.getList();

        if (list.length < this.paginationSettings.pageSize){
            this.containerSize.height = (list.length + 1) * (this.avgRowHeight + 9) + (this.headerHeight + this.footerHeight);
            
        }
        else {
            if (!this.paginationSettings.enabled)
                this.containerSize.height += this.paginatorHeight;

            this.paginationSettings = {
                enabled: true,
                showControlPanel: true,
                pageSize: 10
            }
        }

        let self = this;
        setTimeout(function(){
            self.treegrid.updateLayout();
        }, 1);
    }

**Note**   Timeout above is required to correctly update the position of the paginator.

The complete sample source code is attached. It is based on treegrid-pagination.ts sample file with little modifications. To test it, extract the content of zip file and replace the quickstart/src/app/samples/treegrid/treegrid-pagination.ts file with it.
[treegrid-pagination-on-demand.zip](https://github.com/lidorsystems/integralui-web/files/1871873/treegrid-pagination-on-demand.zip)

**Comment by Lidor-Systems** [comment]
Here is also an article that explains: [Show Scrollbars on Mouse Over in Angular Tree Grid](http://www.lidorsystems.com/support/articles/angular/treegrid/tree-grid-show-scroll-mouse-hover.aspx)

**Comment by NexPlex** [comment]
Hi, I purchased a license for treegrid. now i'm getting this error. 

Can't bind to 'iuiDropDown' since it isn't a known property of 'div'. <div [ERROR ->][iuiDropDown]="cell.dropdown"

**Comment by Lidor-Systems** [comment]
The error states that the iuiDropDown is not recognized. This happens because the IntegralUIDropDown directive is a standalone directive (which is not part of the IntegralUITreeGridModule), it is included in the IntegralUICommonModule. 

To solve this is simple, you need to import the IntegralUICommonModule like this:

```
import { IntegralUICommonModule} from './integralui/integralui.common.module';
import { IntegralUITreeGridModule } from './integralui/integralui.treegrid.module';

@NgModule({
  imports:      [ IntegralUICommonModule, IntegralUITreeGridModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```

This module exports the IntegralUIDropDown directive and now you can use it within your application. 

NOTE   Make sure the path to modules is correct within your application. In above case, it is presumed that the integralui folder is located in the same folder as the app.module.ts file.

There are other components as part of this module, here is a list:

IntegralUIButton, 
IntegralUICheckBox,
IntegralUIComboBox,
IntegralUIDialog,
IntegralUIDropDown,
IntegralUIFrame,
IntegralUIListItem,
IntegralUIListScroller,
IntegralUINumericUpDown,
IntegralUIPaginator, 
IntegralUIProgressBar, 
IntegralUIRadioButton,
IntegralUIRadioGroup,
IntegralUIRange,
IntegralUIRating, 
IntegralUIResize,
IntegralUIScrollBar,
IntegralUISlider,
IntegralUISplitter,
IntegralUITooltip

These are common components, usable as a a standalone or inside some other component like the TreeGrid.

**Comment by NexPlex** [comment]
thank you. I have two questions:

1. For my screen size/pagination logic, I'm trying to find out the total number of expanded visible rows in the grid. 
**any suggestions?**

2. I am having some "focus" challenges when uses edit a row:

On desktops, the first cell and text are selected on Edit. I can't "unselect" the text and keep the cursor in the input element without several clicks. 

On Mobile and phone, I cannot get the cursor or focus on any of the <input tags. No input at all.

**any suggestions?**  
How does [iuiFocus] work is there any documentation on this?

**Comment by Lidor-Systems** [comment]
1. When using pagination, the data is divided in multiple pages. Each page has a number of rows determined by the pageSize. This number of rows affects the root rows per page, not total number of rows per page.

The best way to get a list of all visible rows (child rows of collapsed rows are excluded), is to call the getList method with argument set to 'current', like this:

```
    showVisibleRows(){
        let list = this.treegrid.getList('current');
        console.log(list);
    }
```

To get which page is currently displayed, use the currentPage method, like this:

```
    let activePage = this.treegrid.currentPage();
```

2. We need more details on how this is implemented on your side. Can you give us sample code?

> How does [iuiFocus] work is there any documentation on this?

iuiFocus is very simple directive, it sets the input focus to any element to which this directive is attached. This allows you to change the focus to specific element from code, by simply adding a true value to the directive. 

There is nothing else in this directive, just setting true or false values. Setting a value to false, doesn't clear the focus. The focus is changed by the user action or by setting true value of iuiFocus to some other element.
