### ISSUE TITLE
treegrid expand box cannot be created correctly

### ISSUE THREAD

**Issue by zhuyc110** [lidorsystems/integralui-web-angular#6]
Hi,

I'm investigating the treegrid component, which behaves very good when there are lots of data.

But I'm facing a issue, that the expand box cannot be created correctly, while with double click on a row, its children rows can be presented. See the pic below, the 'Floor' is the child of 'Building' and the 'Room's are the children of 'Floor'.
![GIF](https://user-images.githubusercontent.com/8545052/54667046-5d706c00-4b26-11e9-93b9-7dc8a1b8195d.gif)

I checked the HTML elements, for the demo on official site, the expand box span is 
`<span class="iui-treegrid-expand-box iui-treegrid-expand-box-close"></span>`
while the one of mine is 
`<span ng-reflect-iui-template-outlet-context="[object Object]" ng-reflect-iui-template-outlet="[object Object]"></span>`

I tried to google something but found nothing, did I miss anything?

Thanks for your help!

**Comment by zhuyc110** [comment]
Well, a stupid question, The reason is that I set 'expandColumnIndex'= 3, this make the expand box to be shown on the 3rd Column, I think.

**Comment by Lidor-Systems** [comment]
It's good that you have found a solution quickly.

If you have any questions or need further help, don't hesitate to contact us directly at support@lidorsystems.com.
