### ISSUE TITLE
Treeview trigger expand/collapse by double click does not work sometimes

### ISSUE THREAD

**Issue by Jinzhg** [lidorsystems/integralui-web-angular#8]
Hi,

I found  a issue about the double click to expand/collapse a tree node.

If the interval time is very short between two double click operations, sometimes no responds(i.e. It does not been expand/collapse). I tested it on [treeview demo](https://www.lidorsystems.com/products/web/studio/samples/angular/#/treeview/keyboard) page.

Could you give me some suggestions? Thanks.

**Comment by Lidor-Systems** [comment]
There is nothing unusual here, we are using standard dblclick event to expand/collapse the item. There must be some short delay between two double clicks, it is the way this event works.

**Comment by Lidor-Systems** [comment]
You can override this event in your code. By handling the itemDblClick event and setting the event cancel field to true, the built-in toggle functionality will not happen.

**HTML**
```  
<iui-treeview #treeview [items]="items" (itemDblClick)="onItemDblClick($event)">
```

**Angular**
```
    onItemDblClick(e: any){
        e.cancel = true;
    }
```

Then you can handle the dblclick event from the item template and add your own code for expand/collapse of items:

**HTML**
```
<iui-treeview #treeview [items]="items" (itemDblClick)="onItemDblClick($event)">
      <ng-template let-item>
           <div class="treeview-fsld-item-label" (dblclick)="customItemDblClick($event, item)">{{item.text}}</div>
      </ng-template>
</iui-treeview>
```

**Angular**
```
    customItemDblClick(e: any, item: any){
        this.treeview.toggle(item);
    }
```
